### ISSUE TITLE
Syntax highlighting breaks with bracket in single quotes

### ISSUE THREAD

**Issue by saltysylvi** [razetime/bqn-vscode#23]
![image](https://user-images.githubusercontent.com/110631721/221249504-bfe813f8-b23e-4804-a7bf-8d481d93bce2.png)

This happens with all 3 bracket types (parentheses, curly braces, and square brackets) and really bugs me. Many thanks for your work on this excellent extension!

**Comment by razetime** [comment]
do you have a rainbow brackets extension installed?

**Comment by saltysylvi** [comment]
It would appear so, since my brackets look like this:
![image](https://user-images.githubusercontent.com/110631721/221366764-7b20a89f-1fc0-42d2-a6be-485dcd7ba6a4.png)

Yet my extensions pane doesn't show one:
![image](https://user-images.githubusercontent.com/110631721/221366816-67fa2167-422e-495c-92d3-0ba0f439c983.png)

I'm using VSCodium if that matters:
![image](https://user-images.githubusercontent.com/110631721/221366854-88d6e52c-4531-435b-875f-046bb97f6044.png)

**Comment by mk12** [comment]
VS Code has had built-in bracket pair colorization since 1.60, enabled by default since 1.67:

* [August 2021 (version 1.60) - High performance bracket pair colorization](https://code.visualstudio.com/updates/v1_60#_high-performance-bracket-pair-colorization)
* [How we made bracket pair colorization 10,000x faster in Visual Studio Code](https://code.visualstudio.com/blogs/2021/09/29/bracket-pair-colorization)
* [April 2022 (version 1.67) - Bracket pair colorization enabled by default](https://code.visualstudio.com/updates/v1_67#_bracket-pair-colorization-enabled-by-default)

**Comment by razetime** [comment]
with the exact line you've given, I get this: 
![image](https://user-images.githubusercontent.com/11015319/221514326-1a9e7dd6-03e6-4bb4-8aad-92202abe5536.png)
do you have a larger example? please paste it as text.

**Comment by razetime** [comment]
seems like this is a problem with the current version on the marketplace, the latest dev version seems to correct it.

**Comment by saltysylvi** [comment]
Oh okay cool. I'll close this then. Thanks for looking into it. Do you have any plans for when the dev version will be published on the marketplace next?

**Comment by razetime** [comment]
I will publish a version today. Was planning to delay it till bqncrate support, but now is ok.

**Comment by saltysylvi** [comment]
Awesome, thanks. Just got the new version and the problem is fixed!
